[package]
name = "fla"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest_derive = "2.4"
pest = "2.4"

[dependencies.clap]
version = "4.0"
features = ["derive"]

[profile.release]
opt-level = "s"