root = {(newline | pair)*}

pair = {key ~ "{" ~ value ~ "}" }

key = {(!"{" ~ ANY)+ }

value = {(node | text)+ }

node = {node_char ~ node_text ~ "}"}

node_char = _{newline ~ space* ~ speech ~ space* ~ "{"}

node_text = {(!"}" ~ ANY)+}

text = {(!(node_char | "}") ~ ANY)+}

speech = {"n" | "v" | "o" | "adj" | "adv" | "prep" | "pron"}

space = _{WHITE_SPACE}

newline = _{NEWLINE | comment}

comment = {"#" ~ space ~ (!NEWLINE ~ ANY)+}
