root = {(newline | pair)*}

pair = {key ~ "{" ~ value ~ "}" }

key = {(key_text | "{{" ~ cloze ~ "}}")+}

key_text = {(!"{" ~ ANY)+}

cloze = {(!"}}" ~ ANY)+}

value = {(node | value_text)+ }

node = {node_char ~ node_text ~ "}"}

node_char = _{newline ~ space* ~ speech ~ space* ~ "{"}

node_text = {(!"}" ~ ANY)+}

value_text = {(!(node_char | "}") ~ ANY)+}

speech = {"n" | "v" | "o" | "adj" | "adv" | "prep" | "pron"}

space = _{WHITE_SPACE}

newline = _{NEWLINE}
